// Generated by https://quicktype.io

export interface Producto {
    id:          number;
    title:       string;
    price:       number;
    description: string;
    images:      string[];
    creationAt:  string;
    updatedAt:   string;
    category:    Category[];
}

export interface Category {
    id:         number;
    name:       Name;
    image:      string;
    creationAt: string;
    updatedAt:  string;
}

export enum Name {
    Clothes = "clothes",
    Electronics = "Electronics",
    Furniture = "Furniture",
    Others = "Others",
    Shoes = "Shoes",
}
